<a href="https://colab.research.google.com/github/kimjaehwankimjaehwan/Project2/blob/main/Preprocessing_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
df = pd.read_csv('/content/drive/MyDrive/환경프로젝트/OBS_ASOS_TIM_2017 전체.csv',encoding='cp949')

df.head()

<ipython-input-13-007b9f5d29b1>:1: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/drive/MyDrive/환경프로젝트/OBS_ASOS_TIM_2017 전체.csv',encoding='cp949')

,지점,지점명,일시,기온(°C),기온 QC플래그,강수량(mm),강수량 QC플래그,풍속(m/s),풍속 QC플래그,풍향(16방위),...,최저운고(100m ),시정(10m),지면상태(지면상태코드),현상번호(국내식),지면온도(°C),지면온도 QC플래그,5cm 지중온도(°C),10cm 지중온도(°C),20cm 지중온도(°C),30cm 지중온도(°C)
0,90,속초,2017-01-01 1:00,3.4,0.0,NaN,NaN,1.4,0.0,250.0,...,NaN,1883.0,NaN,NaN,0.9,0.0,NaN,NaN,NaN,NaN
1,90,속초,2017-01-01 2:00,4.6,0.0,NaN,NaN,2.3,0.0,320.0,...,NaN,2000.0,NaN,NaN,0.9,0.0,NaN,NaN,NaN,NaN
2,90,속초,2017-01-01 3:00,4.1,0.0,NaN,NaN,1.4,0.0,270.0,...,NaN,1986.0,NaN,NaN,0.8,0.0,NaN,NaN,NaN,NaN
3,90,속초,2017-01-01 4:00,3.7,0.0,NaN,NaN,1.0,0.0,230.0,...,NaN,2000.0,NaN,NaN,0.7,0.0,NaN,NaN,NaN,NaN
4,90,속초,2017-01-01 5:00,4.1,0.0,NaN,NaN,1.4,0.0,250.0,...,NaN,2000.0,NaN,NaN,0.6,0.0,NaN,NaN,NaN,NaN

In [16]:
filtered_df = df[df['지점'].isin([105, 100, 106, 104, 93, 214, 90, 121, 114, 211, 217, 95, 101, 216, 212])]

In [15]:
filtered_df.head()

,지점,지점명,일시,기온(°C),기온 QC플래그,강수량(mm),강수량 QC플래그,풍속(m/s),풍속 QC플래그,풍향(16방위),...,최저운고(100m ),시정(10m),지면상태(지면상태코드),현상번호(국내식),지면온도(°C),지면온도 QC플래그,5cm 지중온도(°C),10cm 지중온도(°C),20cm 지중온도(°C),30cm 지중온도(°C)
0,90,속초,2017-01-01 1:00,3.4,0.0,NaN,NaN,1.4,0.0,250.0,...,NaN,1883.0,NaN,NaN,0.9,0.0,NaN,NaN,NaN,NaN
1,90,속초,2017-01-01 2:00,4.6,0.0,NaN,NaN,2.3,0.0,320.0,...,NaN,2000.0,NaN,NaN,0.9,0.0,NaN,NaN,NaN,NaN
2,90,속초,2017-01-01 3:00,4.1,0.0,NaN,NaN,1.4,0.0,270.0,...,NaN,1986.0,NaN,NaN,0.8,0.0,NaN,NaN,NaN,NaN
3,90,속초,2017-01-01 4:00,3.7,0.0,NaN,NaN,1.0,0.0,230.0,...,NaN,2000.0,NaN,NaN,0.7,0.0,NaN,NaN,NaN,NaN
4,90,속초,2017-01-01 5:00,4.1,0.0,NaN,NaN,1.4,0.0,250.0,...,NaN,2000.0,NaN,NaN,0.6,0.0,NaN,NaN,NaN,NaN

In [17]:
filtered_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 122299 entries, 0 to 471602
Data columns (total 38 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   지점             122299 non-null  int64
 1   지점명            122299 non-null  object
 2   일시             122299 non-null  object
 3   기온(°C)         122287 non-null  float64
 4   기온 QC플래그       121949 non-null  float64
 5   강수량(mm)        10952 non-null   float64
 6   강수량 QC플래그      30505 non-null   float64
 7   풍속(m/s)        122289 non-null  float64
 8   풍속 QC플래그       110222 non-null  float64
 9   풍향(16방위)       122289 non-null  float64
 10  풍향 QC플래그       110222 non-null  float64
 11  습도(%)          122204 non-null  float64
 12  습도 QC플래그       121949 non-null  float64
 13  증기압(hPa)       122225 non-null  float64
 14  이슬점온도(°C)      122223 non-null  float64
 15  현지기압(hPa)      122285 non-null  float64
 16  현지기압 QC플래그     121949 non-null  float64
 17  해면기압(hPa)      122285 non-null  float64
 18  해면기압 QC플래그     121949 non-null  float64
 19  일조(hr)         66852 non-null   float64
 20  일조 QC플래그       115765 non-null  float64
 21  일사(MJ/m2)      28652 non-null   float64
 22  일사 QC플래그       119504 non-null  float64
 23  적설(cm)         2734 non-null    float64
 24  3시간신적설(cm)     47 non-null      float64
 25  전운량(10분위)      13633 non-null   float64
 26  중하층운량(10분위)    15527 non-null   float64
 27  운형(운형약어)       9317 non-null    object
 28  최저운고(100m )    8333 non-null    float64
 29  시정(10m)        120323 non-null  float64
 30  지면상태(지면상태코드)   0 non-null       float64
 31  현상번호(국내식)      4050 non-null    float64
 32  지면온도(°C)       122230 non-null  float64
 33  지면온도 QC플래그     121949 non-null  float64
 34  5cm 지중온도(°C)   43617 non-null   float64
 35  10cm 지중온도(°C)  43671 non-null   float64
 36  20cm 지중온도(°C)  43679 non-null   float64
 37  30cm 지중온도(°C)  43679 non-null   float64
dtypes: float64(34), int64(1), object(3)
memory usage: 36.4+ MB

In [18]:
selected_columns = [
    '일시', '기온(°C)',  '강수량(mm)',
    '풍속(m/s)',  '풍향(16방위)', '습도(%)',
    '증기압(hPa)', '이슬점온도(°C)', '현지기압(hPa)',
    '해면기압(hPa)', '일조(hr)',  '일사(MJ/m2)',
    '적설(cm)', '3시간신적설(cm)', '전운량(10분위)', '중하층운량(10분위)',
    '최저운고(100m )', '시정(10m)',
    '지면온도(°C)',  '5cm 지중온도(°C)',
    '10cm 지중온도(°C)', '20cm 지중온도(°C)', '30cm 지중온도(°C)'
]
filtered_df = filtered_df[selected_columns]
filtered_df.head()

,일시,기온(°C),강수량(mm),풍속(m/s),풍향(16방위),습도(%),증기압(hPa),이슬점온도(°C),현지기압(hPa),해면기압(hPa),...,3시간신적설(cm),전운량(10분위),중하층운량(10분위),최저운고(100m ),시정(10m),지면온도(°C),5cm 지중온도(°C),10cm 지중온도(°C),20cm 지중온도(°C),30cm 지중온도(°C)
0,2017-01-01 1:00,3.4,NaN,1.4,250.0,53.0,4.2,-5.2,1024.3,1026.6,...,NaN,NaN,NaN,NaN,1883.0,0.9,NaN,NaN,NaN,NaN
1,2017-01-01 2:00,4.6,NaN,2.3,320.0,48.0,4.1,-5.4,1024.1,1026.4,...,NaN,NaN,NaN,NaN,2000.0,0.9,NaN,NaN,NaN,NaN
2,2017-01-01 3:00,4.1,NaN,1.4,270.0,49.0,4.0,-5.6,1024.3,1026.6,...,NaN,NaN,NaN,NaN,1986.0,0.8,NaN,NaN,NaN,NaN
3,2017-01-01 4:00,3.7,NaN,1.0,230.0,48.0,3.8,-6.3,1023.9,1026.2,...,NaN,NaN,NaN,NaN,2000.0,0.7,NaN,NaN,NaN,NaN
4,2017-01-01 5:00,4.1,NaN,1.4,250.0,46.0,3.8,-6.5,1023.7,1026.0,...,NaN,NaN,NaN,NaN,2000.0,0.6,NaN,NaN,NaN,NaN

In [19]:
grouped_df = filtered_df.groupby('일시').mean().reset_index()

print(grouped_df.head())

                 일시    기온(°C)  강수량(mm)   풍속(m/s)    풍향(16방위)      습도(%)  \
0  2017-01-01 10:00  1.064286      NaN  1.735714  122.857143  72.857143
1  2017-01-01 11:00  2.892857      NaN  1.435714  158.571429  65.000000
2  2017-01-01 12:00  4.021429      NaN  2.014286  190.000000  60.857143
3  2017-01-01 13:00  5.121429      NaN  2.042857  184.285714  57.500000
4  2017-01-01 14:00  5.857143      NaN  2.435714  193.571429  54.928571

   증기압(hPa)  이슬점온도(°C)    현지기압(hPa)    해면기압(hPa)  ...  3시간신적설(cm)  전운량(10분위)  \
0  4.571429  -4.071429  1003.400000  1030.164286  ...         NaN        6.5
1  4.557143  -4.178571  1003.271429  1029.835714  ...         NaN        7.5
2  4.714286  -3.735714  1002.257143  1028.685714  ...         NaN        6.5
3  4.907143  -3.135714  1001.242857  1027.557143  ...         NaN        7.0
4  4.985714  -2.835714  1000.571429  1026.792857  ...         NaN        6.5

   중하층운량(10분위)  최저운고(100m )      시정(10m)  지면온도(°C)  5cm 지중온도(°C)  \
0          5.0          6.0  1247.714286  0.528571          0.84
1          5.0          6.0  1279.571429  1.164286          1.14
2          3.0         10.0  1338.928571  2.200000          1.38
3          3.5         10.0  1307.642857  3.264286          1.58
4          4.5         20.0  1246.928571  3.192857          1.90

   10cm 지중온도(°C)  20cm 지중온도(°C)  30cm 지중온도(°C)
0           0.86           1.96           2.74
1           0.92           1.96           2.76
2           1.10           1.96           2.76
3           1.22           1.98           2.72
4           1.38           2.00           2.74

[5 rows x 23 columns]

In [20]:
sorted_df = grouped_df.sort_values(by='일시', ascending=True).reset_index(drop=True)

print(sorted_df.head())

                 일시    기온(°C)  강수량(mm)   풍속(m/s)    풍향(16방위)      습도(%)  \
0  2017-01-01 10:00  1.064286      NaN  1.735714  122.857143  72.857143
1  2017-01-01 11:00  2.892857      NaN  1.435714  158.571429  65.000000
2  2017-01-01 12:00  4.021429      NaN  2.014286  190.000000  60.857143
3  2017-01-01 13:00  5.121429      NaN  2.042857  184.285714  57.500000
4  2017-01-01 14:00  5.857143      NaN  2.435714  193.571429  54.928571

   증기압(hPa)  이슬점온도(°C)    현지기압(hPa)    해면기압(hPa)  ...  3시간신적설(cm)  전운량(10분위)  \
0  4.571429  -4.071429  1003.400000  1030.164286  ...         NaN        6.5
1  4.557143  -4.178571  1003.271429  1029.835714  ...         NaN        7.5
2  4.714286  -3.735714  1002.257143  1028.685714  ...         NaN        6.5
3  4.907143  -3.135714  1001.242857  1027.557143  ...         NaN        7.0
4  4.985714  -2.835714  1000.571429  1026.792857  ...         NaN        6.5

   중하층운량(10분위)  최저운고(100m )      시정(10m)  지면온도(°C)  5cm 지중온도(°C)  \
0          5.0          6.0  1247.714286  0.528571          0.84
1          5.0          6.0  1279.571429  1.164286          1.14
2          3.0         10.0  1338.928571  2.200000          1.38
3          3.5         10.0  1307.642857  3.264286          1.58
4          4.5         20.0  1246.928571  3.192857          1.90

   10cm 지중온도(°C)  20cm 지중온도(°C)  30cm 지중온도(°C)
0           0.86           1.96           2.74
1           0.92           1.96           2.76
2           1.10           1.96           2.76
3           1.22           1.98           2.72
4           1.38           2.00           2.74

[5 rows x 23 columns]

In [21]:
sorted_df.to_csv('강원도_2017.csv', index=False, encoding='utf-8-sig')

In [28]:
regions = {
    '강원도_2017.csv' : [105, 100, 106, 104, 93, 214, 90, 121, 114, 211, 217, 95, 101, 216, 212],
    '경기도_2017.csv': [98, 119, 202, 203, 99],
    '경상남도_2017.csv' : [294, 284, 253, 295, 288, 255, 289, 257, 263, 192, 155, 162, 264, 285],
    '경상북도_2017.csv' : [283, 279, 273, 271, 137, 136, 277, 272, 281, 115, 130, 278, 276, 138],
    '광주광역시_2017.csv': [156],
    "대구광역시_2017.csv": [143],
    "대전광역시_2017.csv": [133],
    "부산광역시_2017.csv": [159, 296],
    '서울특별시_2017.csv': [108, 116],
    '울산광역시_2017.csv': [152],
    '인천광역시_2017.csv': [201, 102, 112],
    '전라남도_2017.csv': [259, 262, 266, 165, 164, 258, 174, 168, 252, 170, 260, 256, 175, 268, 261, 169],
    '전라북도_2017.csv': [172, 251, 140, 247, 243, 254, 244, 248, 146, 245],
    '제주도_2017.csv': [185, 189, 187, 188, 265, 184],
    '충청남도_2017.csv': [238, 235, 236, 129, 232, 177],
    '충청북도_2017.csv': [226, 181, 221, 131, 135, 127]
}

for file_name, 지점_list in regions.items():
  filtered_df_2 = df[df['지점'].isin(지점_list)]
  selected_columns = [
      '일시', '기온(°C)',  '강수량(mm)',
      '풍속(m/s)',  '풍향(16방위)', '습도(%)',
      '증기압(hPa)', '이슬점온도(°C)', '현지기압(hPa)',
      '해면기압(hPa)', '일조(hr)',  '일사(MJ/m2)',
      '적설(cm)', '3시간신적설(cm)', '전운량(10분위)', '중하층운량(10분위)',
      '최저운고(100m )', '시정(10m)',
      '지면온도(°C)',  '5cm 지중온도(°C)',
      '10cm 지중온도(°C)', '20cm 지중온도(°C)', '30cm 지중온도(°C)'
  ]
  filtered_df_2 = filtered_df_2[selected_columns]
  grouped_df_2 = filtered_df_2.groupby('일시').mean().reset_index()
  sorted_df_2 = grouped_df_2.sort_values(by='일시', ascending=True).reset_index(drop=True)
  sorted_df_2.to_csv(file_name, index=False, encoding='utf-8-sig')

In [31]:
df = pd.read_csv('/content/drive/MyDrive/환경프로젝트/OBS_ASOS_TIM_2018 전체.csv',encoding='cp949')
df.head()

<ipython-input-31-410a8ea1338f>:1: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/drive/MyDrive/환경프로젝트/OBS_ASOS_TIM_2018 전체.csv',encoding='cp949')

,지점,지점명,일시,기온(°C),기온 QC플래그,강수량(mm),강수량 QC플래그,풍속(m/s),풍속 QC플래그,풍향(16방위),...,최저운고(100m ),시정(10m),지면상태(지면상태코드),현상번호(국내식),지면온도(°C),지면온도 QC플래그,5cm 지중온도(°C),10cm 지중온도(°C),20cm 지중온도(°C),30cm 지중온도(°C)
0,90,속초,2018-01-01 1:00,-2.1,0.0,NaN,NaN,1.7,0.0,230.0,...,NaN,2000.0,NaN,NaN,-2.7,0.0,NaN,NaN,NaN,NaN
1,90,속초,2018-01-01 2:00,-2.1,0.0,NaN,NaN,1.4,0.0,160.0,...,NaN,2000.0,NaN,NaN,-3.0,0.0,NaN,NaN,NaN,NaN
2,90,속초,2018-01-01 3:00,-2.2,0.0,NaN,NaN,0.9,0.0,230.0,...,NaN,2000.0,NaN,NaN,-3.2,0.0,NaN,NaN,NaN,NaN
3,90,속초,2018-01-01 4:00,-2.0,0.0,NaN,NaN,1.2,0.0,250.0,...,NaN,2000.0,NaN,NaN,-3.3,0.0,NaN,NaN,NaN,NaN
4,90,속초,2018-01-01 5:00,-1.7,0.0,NaN,NaN,1.4,0.0,270.0,...,NaN,2000.0,NaN,NaN,-3.1,0.0,NaN,NaN,NaN,NaN

In [36]:
regions = {
    '강원도': [105, 100, 106, 104, 93, 214, 90, 121, 114, 211, 217, 95, 101, 216, 212],
    '경기도': [98, 119, 202, 203, 99],
    '경상남도': [294, 284, 253, 295, 288, 255, 289, 257, 263, 192, 155, 162, 264, 285],
    '경상북도': [283, 279, 273, 271, 137, 136, 277, 272, 281, 115, 130, 278, 276, 138],
    '광주광역시': [156],
    "대구광역시": [143],
    "대전광역시": [133],
    "부산광역시": [159, 296],
    '서울특별시': [108, 116],
    '울산광역시': [152],
    '인천광역시': [201, 102, 112],
    '전라남도': [259, 262, 266, 165, 164, 258, 174, 168, 252, 170, 260, 256, 175, 268, 261, 169],
    '전라북도': [172, 251, 140, 247, 243, 254, 244, 248, 146, 245],
    '제주도': [185, 189, 187, 188, 265, 184],
    '충청남도': [238, 235, 236, 129, 232, 177],
    '충청북도': [226, 181, 221, 131, 135, 127]
}

for year in range(2017, 2024):
  df = pd.read_csv(f'/content/drive/MyDrive/환경프로젝트/OBS_ASOS_TIM_{year} 전체.csv',encoding='cp949')
  for region_name, 지점_list in regions.items():

      filtered_df_2 = df[df['지점'].isin(지점_list)]

      selected_columns = [
          '일시', '기온(°C)',  '강수량(mm)',
          '풍속(m/s)',  '풍향(16방위)', '습도(%)',
          '증기압(hPa)', '이슬점온도(°C)', '현지기압(hPa)',
          '해면기압(hPa)', '일조(hr)',  '일사(MJ/m2)',
          '적설(cm)', '3시간신적설(cm)', '전운량(10분위)', '중하층운량(10분위)',
          '최저운고(100m )', '시정(10m)',
          '지면온도(°C)',  '5cm 지중온도(°C)',
          '10cm 지중온도(°C)', '20cm 지중온도(°C)', '30cm 지중온도(°C)'
      ]
      filtered_df_2 = filtered_df_2[selected_columns]

      grouped_df_2 = filtered_df_2.groupby('일시').mean().reset_index()

      sorted_df_2 = grouped_df_2.sort_values(by='일시', ascending=True).reset_index(drop=True)

      file_name = f'{region_name}_{year}.csv'

      file_path = f'/content/drive/MyDrive/환경프로젝트/{file_name}'

      sorted_df_2.to_csv(file_path, index=False, encoding='utf-8-sig')

      print(f"{file_name} 저장 완료")

<ipython-input-36-75d511c072b3>:21: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f'/content/drive/MyDrive/환경프로젝트/OBS_ASOS_TIM_{year} 전체.csv',encoding='cp949')

강원도_2017.csv 저장 완료
경기도_2017.csv 저장 완료
경상남도_2017.csv 저장 완료
경상북도_2017.csv 저장 완료
광주광역시_2017.csv 저장 완료
대구광역시_2017.csv 저장 완료
대전광역시_2017.csv 저장 완료
부산광역시_2017.csv 저장 완료
서울특별시_2017.csv 저장 완료
울산광역시_2017.csv 저장 완료
인천광역시_2017.csv 저장 완료
전라남도_2017.csv 저장 완료
전라북도_2017.csv 저장 완료
제주도_2017.csv 저장 완료
충청남도_2017.csv 저장 완료
충청북도_2017.csv 저장 완료

<ipython-input-36-75d511c072b3>:21: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f'/content/drive/MyDrive/환경프로젝트/OBS_ASOS_TIM_{year} 전체.csv',encoding='cp949')

강원도_2018.csv 저장 완료
경기도_2018.csv 저장 완료
경상남도_2018.csv 저장 완료
경상북도_2018.csv 저장 완료
광주광역시_2018.csv 저장 완료
대구광역시_2018.csv 저장 완료
대전광역시_2018.csv 저장 완료
부산광역시_2018.csv 저장 완료
서울특별시_2018.csv 저장 완료
울산광역시_2018.csv 저장 완료
인천광역시_2018.csv 저장 완료
전라남도_2018.csv 저장 완료
전라북도_2018.csv 저장 완료
제주도_2018.csv 저장 완료
충청남도_2018.csv 저장 완료
충청북도_2018.csv 저장 완료

<ipython-input-36-75d511c072b3>:21: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f'/content/drive/MyDrive/환경프로젝트/OBS_ASOS_TIM_{year} 전체.csv',encoding='cp949')

강원도_2019.csv 저장 완료
경기도_2019.csv 저장 완료
경상남도_2019.csv 저장 완료
경상북도_2019.csv 저장 완료
광주광역시_2019.csv 저장 완료
대구광역시_2019.csv 저장 완료
대전광역시_2019.csv 저장 완료
부산광역시_2019.csv 저장 완료
서울특별시_2019.csv 저장 완료
울산광역시_2019.csv 저장 완료
인천광역시_2019.csv 저장 완료
전라남도_2019.csv 저장 완료
전라북도_2019.csv 저장 완료
제주도_2019.csv 저장 완료
충청남도_2019.csv 저장 완료
충청북도_2019.csv 저장 완료

<ipython-input-36-75d511c072b3>:21: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f'/content/drive/MyDrive/환경프로젝트/OBS_ASOS_TIM_{year} 전체.csv',encoding='cp949')

강원도_2020.csv 저장 완료
경기도_2020.csv 저장 완료
경상남도_2020.csv 저장 완료
경상북도_2020.csv 저장 완료
광주광역시_2020.csv 저장 완료
대구광역시_2020.csv 저장 완료
대전광역시_2020.csv 저장 완료
부산광역시_2020.csv 저장 완료
서울특별시_2020.csv 저장 완료
울산광역시_2020.csv 저장 완료
인천광역시_2020.csv 저장 완료
전라남도_2020.csv 저장 완료
전라북도_2020.csv 저장 완료
제주도_2020.csv 저장 완료
충청남도_2020.csv 저장 완료
충청북도_2020.csv 저장 완료

<ipython-input-36-75d511c072b3>:21: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f'/content/drive/MyDrive/환경프로젝트/OBS_ASOS_TIM_{year} 전체.csv',encoding='cp949')

강원도_2021.csv 저장 완료
경기도_2021.csv 저장 완료
경상남도_2021.csv 저장 완료
경상북도_2021.csv 저장 완료
광주광역시_2021.csv 저장 완료
대구광역시_2021.csv 저장 완료
대전광역시_2021.csv 저장 완료
부산광역시_2021.csv 저장 완료
서울특별시_2021.csv 저장 완료
울산광역시_2021.csv 저장 완료
인천광역시_2021.csv 저장 완료
전라남도_2021.csv 저장 완료
전라북도_2021.csv 저장 완료
제주도_2021.csv 저장 완료
충청남도_2021.csv 저장 완료
충청북도_2021.csv 저장 완료

<ipython-input-36-75d511c072b3>:21: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f'/content/drive/MyDrive/환경프로젝트/OBS_ASOS_TIM_{year} 전체.csv',encoding='cp949')

강원도_2022.csv 저장 완료
경기도_2022.csv 저장 완료
경상남도_2022.csv 저장 완료
경상북도_2022.csv 저장 완료
광주광역시_2022.csv 저장 완료
대구광역시_2022.csv 저장 완료
대전광역시_2022.csv 저장 완료
부산광역시_2022.csv 저장 완료
서울특별시_2022.csv 저장 완료
울산광역시_2022.csv 저장 완료
인천광역시_2022.csv 저장 완료
전라남도_2022.csv 저장 완료
전라북도_2022.csv 저장 완료
제주도_2022.csv 저장 완료
충청남도_2022.csv 저장 완료
충청북도_2022.csv 저장 완료

<ipython-input-36-75d511c072b3>:21: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f'/content/drive/MyDrive/환경프로젝트/OBS_ASOS_TIM_{year} 전체.csv',encoding='cp949')

강원도_2023.csv 저장 완료
경기도_2023.csv 저장 완료
경상남도_2023.csv 저장 완료
경상북도_2023.csv 저장 완료
광주광역시_2023.csv 저장 완료
대구광역시_2023.csv 저장 완료
대전광역시_2023.csv 저장 완료
부산광역시_2023.csv 저장 완료
서울특별시_2023.csv 저장 완료
울산광역시_2023.csv 저장 완료
인천광역시_2023.csv 저장 완료
전라남도_2023.csv 저장 완료
전라북도_2023.csv 저장 완료
제주도_2023.csv 저장 완료
충청남도_2023.csv 저장 완료
충청북도_2023.csv 저장 완료